### ISSUE TITLE
Drag'n'drop not working in Obsidian

### ISSUE THREAD

**Issue by j-palindrome** [artem-barmin/obsidian-block-drag-n-drop#37]
When dragging and dropping a bulleted list with the Live Preview editor, I get this error:

```
TypeError: Cannot read properties of undefined (reading 'state')
    at DOMtoLine (plugin:obsidian-drag-n-drop-plugin:11092:28)
    at highlightWholeItem (plugin:obsidian-drag-n-drop-plugin:11132:18)
    at Object.dragenter (plugin:obsidian-drag-n-drop-plugin:11183:13)
    at e.runCustomHandlers (app.js:1:422880)
    at HTMLDivElement.<anonymous> (app.js:1:422663)
```

**Comment by TheGuySwann** [comment]
I'm having trouble with it too. I want so bad to be able to drag and drop like I always did in Roam. Has there been any update about this?
